FROM node:20

WORKDIR /app

COPY package-lock.json ./
COPY packages/teestack/package.json ./

RUN npm i

COPY packages/teestack/pb ./pb
COPY packages/teestack/server.ts ./

CMD ["npm", "run", "dev:server"]